[general]
import = ["~/.config/alacritty/themes/catppuccin-mocha.toml"]

[font]
size = 10

normal.family = "CodeNewRoman Nerd Font Propo"
bold.family = "CodeNewRoman Nerd Font Propo"
italic.family = "CodeNewRoman Nerd Font Propo"
bold_italic.family = "CodeNewRoman Nerd Font Propo"

[keyboard]
bindings = [
  { key = "M", mods = "None", mode = "Vi|~Search", action = "Left" },
  { key = "H", mods = "None", mode = "Vi|~Search", action = "Down" },
  { key = "T", mods = "None", mode = "Vi|~Search", action = "Up" },
  { key = "S", mods = "None", mode = "Vi|~Search", action = "Right" },
]
