backend = "glx";
vsync = true;

inactive-dim = 0.2;
inactive-dim-fixed = true;

focus-exclude = [
    "class_g = 'mpv'"
];

shadow = true;

shadow-radius = 20;

shadow-exclude = [
    "!class_g = 'Rofi'"
];
