HOSTNAME=arch
SWAP_SIZE=32GB
ZRAM_SIZE=RAM/2

##
## Efibootmgr setup following `/etc/fstab`
##
EFINAME=Arch

## CPU Encode
# UCODE=amd
UCODE=amd

##
## Login Manager
##
LOGIN_MANAGER=lemurs # sddm gdm lightdm

###
### GPU
###
GPU=nvidia # nvidia amd

##
## Services
##
SERVICES=(NetworkManager bluetooth)

##
## /etc/locale.conf
##
LANG=en_US.UTF-8
KEYMAP=us

##
## timedatectl
##
TIMEZONE=Asia/Singapore

##
## Ollama
## - `ollama`: CPU inference
## - `ollama-vulkan`: Vulkan inference
## - `ollama-cuda`: CUDA inference (nvidia)
## - `ollama-rocm`: ROCM inference (amd)
##
OLLAMA=ollama-cuda
OLLAMA_PATH=/mnt/nvme/Ollama
